version: 2
jobs:
  build:
    working_directory: ~/repo
    docker:
      - image: docker:20.10.21-git

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: install dependencies
          command: |
            apk add --no-cache py-pip
            pip install docker-compose==1.25.0

      - run:
          name: Build App Docker Image
          command: |
            docker-compose build

      # run tests!
      - run:
          name: run tests
          command: |
            docker-compose run --rm rpnet rails db:migrate RAILS_ENV=test
            docker-compose run --rm rpnet bundle exec rspec
